export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// GET
export const GET_STORY_FROM_USER  = 'GET_STORY_FROM_USER';
export const GET_STORY_FROM_USER_SUCCESS  = 'GET_STORY_FROM_USER_SUCCESS';
export const GET_STORY_FROM_USER_ERROR  = 'GET_STORY_FROM_USER_ERROR';
export const RESET_STORY_FROM_USER  = 'RESET_STORY_FROM_USER';

export const GET_STORY_FROM_ID = 'GET_STORY_FROM_ID';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_ERROR = 'GET_STORY_ERROR';
export const RESET_SELECTED_STORY = 'RESET_SELECTED_STORY';

export const GET_LAST_STORIES = 'GET_LAST_STORIES';
export const GET_LAST_STORIES_SUCCESS = 'GET_LAST_STORIES_SUCCESS';
export const GET_LAST_STORIES_ERROR = 'GET_LAST_STORIES_ERROR';
export const RESET_LAST_STORIES = 'RESET_LAST_STORIES';


export const GET_CHAPTER_BY_ID = 'GET_CHAPTER_BY_ID';
export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS';
export const GET_CHAPTER_ERROR = 'GET_CHAPTER_ERROR';
export const RESET_SELECTED_CHAPTER = 'RESET_SELECTED_CHAPTER';

// CREATE
export const CREATE_STORY = 'CREATE_STORY';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_FAILURE = 'CREATE_STORY_FAILURE';
export const RESET_NEW_STORY = 'RESET_NEW_STORY';

export const CREATE_CHAPTER = 'CREATE_CHAPTER';
export const CREATE_CHAPTER_SUCCESS = 'CREATE_CHAPTER_SUCCESS';
export const CREATE_CHAPTER_FAILURE = 'CREATE_CHAPTER_FAILURE';
export const RESET_NEW_CHAPTER = 'RESET_NEW_CHAPTER';

// DELETE
export const DELETE_STORY = 'DELETE_STORY';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_FAILURE = 'DELETE_STORY_FAILURE';
export const RESET_DELETED_STORY = 'RESET_DELETED_STORY';

// EDIT
export const EDIT_STORY = 'EDIT_STORY';
export const EDIT_STORY_SUCCESS = 'EDIT_STORY_SUCCESS';
export const EDIT_STORY_FAILURE = 'EDIT_STORY_FAILURE';
export const RESET_EDIT_STORY = 'RESET_EDIT_STORY';

// EDIT CHAPTER
export const EDIT_CHAPTER = 'EDIT_CHAPTER';
export const EDIT_CHAPTER_SUCCESS = 'EDIT_CHAPTER_SUCCESS';
export const EDIT_CHAPTER_FAILURE = 'EDIT_CHAPTER_FAILURE';
export const RESET_EDIT_CHAPTER = 'RESET_EDIT_CHAPTER';

//Validate post fields like Title, Categries on the server
export const VALIDATE_POST_FIELDS = 'VALIDATE_POST_FIELDS';
export const VALIDATE_POST_FIELDS_SUCCESS = 'VALIDATE_POST_FIELDS_SUCCESS';
export const VALIDATE_POST_FIELDS_FAILURE = 'VALIDATE_POST_FIELDS_FAILURE';
export const RESET_POST_FIELDS = 'RESET_POST_FIELDS';

export const LOAD = 'LOAD';
export const EDIT_MODE = 'EDIT_MODE';
export const EDIT_MODE_RESET = 'EDIT_MODE_RESET';
export const RESET_FORM = 'RESET_FORM';
export const CREATE_MODE = 'CREATE_MODE';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const RESET_SELECTED_USER = 'RESET_SELECTED_USER';